import os
import csv
import random

def autogenerateDataDirectories(target_directory):
    if not os.path.exists(target_directory):
        os.makedirs(target_directory)
    if not os.path.exists(target_directory+"match_stats"):
        os.makedirs(target_directory+"match_stats")
    if not os.path.exists(target_directory+"seasonal_stats"):
        os.makedirs(target_directory+"seasonal_stats")
    if not os.path.exists(target_directory+"telemetry_data"):
        os.makedirs(target_directory+"telemetry_data")

# reservoir sampling from list of player ids
def extractRandomPlayerListFromMatch(samples_filepath, match_dict, samples_count):
    random_players_list_filepath = samples_filepath+"id_list.txt"

    player_id_list = [data["attributes"]["stats"]["playerId"] for data in match_dict["included"] if data["type"] == "participant"]
    random.shuffle(player_id_list)
    player_id_list = player_id_list[:min(len(player_id_list), samples_count)]

    with open(random_players_list_filepath, mode = "a+") as file:
        for id in player_id_list:
            file.write(id+"\n")
    #print(player_id_list)



def writeMatchDataToCsv(filename, match_list):
    fieldnames = ["matchId", "createdAt", "gameMode", "mapName", "isCustomMatch", "duration", "rank", "won",
                    "DBNOs", "assists", "boosts", "damageDealt", "deathType", "headshotKills", "heals",
                    "killPlace", "killPoints", "killPointsDelta", "killStreaks", "kills", "lastKillPoints", "lastWinPoints",
                    "longestKill", "mostDamage", "rankPoints", "revives", "rideDistance", "roadKills", "swimDistance", "teamKills",
                    "timeSurvived", "vehicleDestroys", "walkDistance", "weaponsAcquired", "winPlace", "winPoints", "winPointsDelta",
                    "teammates", "telemetryDataURL"]

    with open(filename, mode='w') as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()

        for match_data in match_list:
            roster_str = ""
            for teammate in match_data["rosterIdList"]:
                roster_str+=teammate["id"]+"&"
            roster_str = roster_str[:-1]

            match_data = {**match_data, **match_data["matchAttributes"], **match_data["playerStats"]}
            match_data["teammates"] = roster_str
            for unused_key in ["titleId", "shardId", "playerId", "stats",
                                "rosterIdList", "won", "tags", "matchAttributes","seasonState",
                                "name", "responseStatus", "playerStats"]:
                match_data.pop(unused_key)
            writer.writerow(match_data)
